negative: negative.c
	clang -o negative -Wall negative.c -lm

describe: describe.c
	clang -o describe -Wall describe.c -lm

ppm_p152: ppm_p152.c
	clang -o ppm_p152 -Wall ppm_p152.c -lm

p152_ppm: p152_ppm.c
	clang -o p152_ppm -Wall p152_ppm.c -lm